name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses & install SDKs
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-35" "build-tools;35.0.0" "platform-tools"

      # Genera el wrapper de Gradle y fija la versión
      - name: Generate Gradle wrapper 8.9
        run: gradle wrapper --gradle-version 8.9

      # Construye con logs detallados usando el wrapper
      - name: Build (verbose)
        run: |
          ./gradlew --version
          ./gradlew assembleDebug --no-daemon --info --stacktrace
        shell: bash

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

